title: FET Loader
description: A simple cheats loader written in AHK
owner: FET Loader Team
owner_url: https://github.com/fetloader

theme: jekyll-theme-cayman

show_links: true

view_url: https://github.com/fetloader
release_url: https://shre.su/221A
tg_channel: https://t.me/ayeloader
vk_group: https://vk.com/ayeloader
ds_server: https://discord.gg/bSgZxY3rQm
donate: https://t.me/m4x3r228/5
