title: FET Loader
theme: jekyll-theme-cayman


release_url: https://github.com/fetloader/fetloader/releases/latest
tg_channel: https://t.me/ayeloader
vk_group: https://vk.com/ayeloader
ds_server: https://discord.gg/bSgZxY3rQm
donate: https://t.me/m4x3r228/5
